---
title: "Flex Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
```


```{r data}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "Central Park, NY", 
      USC00519397 = "Waikiki, HA",
      USS0023B17S = "Waterhole, WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  mutate(prcp = prcp/10)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Recorded Temperature Maximums Overtime at Three Weather Station Locations

```{r}
weather_df %>%
  plot_ly(
    x = ~date, y = ~tmax, type = "scatter", mode = "markers",
    color = ~name, alpha = 0.5) %>%
  layout(title = "Maximum Recorded Temperature Overtime by Weather Station Location", xaxis = list(title = "Date"), yaxis = list(title = "Maximum Temperature (C)"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Recorded Precipitation (cm) by Weather Station Location

```{r}
weather_df %>%
  filter(prcp < 60) %>%
  plot_ly(y = ~prcp, color = ~name, type = "box", colors = "viridis") %>%
  layout(xaxis = list(title = "Location"), yaxis = list(title = "Recorded precipitation (cm)"))
```

### Total Monthly Precipitation in Central Park, NY

```{r}
weather_df %>%
  separate(date, into = c("year", "month", "day"), sep = "-") %>%
  drop_na(prcp) %>%
  filter(name == "Central Park, NY") %>%
  mutate(month = recode_factor(month, "01" = "January", "02" = "February", "03" = "March", "04" = "April", "05" = "May", "06" = "June", "07" = "July", "08" = "August", "09" = "September", "10" = "October", "11" = "November", "12" = "December")) %>%
  group_by(name, month) %>%
  summarise(total_prcp = sum(prcp)) %>%
  plot_ly(x = ~month, y = ~total_prcp, color = ~month, type = "bar", colors = "viridis") %>%
  layout(title = "Total Precipitation by Month in Central Park, NY", xaxis = list(title = "Month"), yaxis = list(title = "Total Precipitation (cm)"))
```

